### ISSUE TITLE
[RFE] Display DO "current config" similar to AS3 tasks/applications

### ISSUE THREAD

**Issue by mwardbopp** [f5devcentral/vscode-f5#170]
It would be great for the extension to discover if DO was installed what was the current declaration and display it in a similar folder structure as AS3/FAST

**Comment by DumpySquare** [comment]
Hey @mwardbopp, thanks for opening this issue.  

Since DO only has a single declaration, like TS/CF, I didn't think it was worth creating a view for those services.  

All those commands can be found via the command palette:

![image](https://user-images.githubusercontent.com/3260966/155607060-9f73bce9-e342-41e8-9f9f-8194ba285369.png)


While the documentation may be a bit dated in some cases, this shows how to click on the DO status bar at the bottom to get the current declaration:  https://f5devcentral.github.io/vscode-f5/#/do_ts?id=do-management-getpost

Does this suite your ask?

**Comment by DumpySquare** [comment]
Hey @mwardbopp, does the above suite your ask or would you still prefer a "view" window on the left like as3?
